import Head from "next/head";
function CustomHead() {
    return (
        <>
            <Head>
                <title>Space-X Launch Program</title>
                <meta name="description" content="Generated by create next app, deployed by Rakshit" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    );
}
export default CustomHead;